# -*- coding: utf-8 -*-
"""ModeloPredictivo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMEuvhCUqv6ZnXzPBfgvdHSM5Xt8u9Is
"""

#Esta linea nos incluye la libreria para trabajar con modelos de IA
import tensorflow as tf
#Con numpy crearemos nuestros datos de entrada
import numpy as np

#Creamos nuestros datos de entrada
celcius = np.array([-40,-10,0,8,15,22,38], dtype = float)
f = np.array([-40,14,32,46,59,72,100], dtype = float)

#Tensorflow, keras
#Creamos nuestra capa que contendra nuestro modelo
capa = tf.keras.layers.Dense(units = 1, input_shape=[1])

#Declaramos nuestro modelo con dicha capa
modelo = tf.keras.Sequential([capa])

#Creando el modelo
modelo.compile(
    optimizer = tf.keras.optimizers.Adam(0.1),

    loss = 'mean_squared_error'
)

print('Inicia el entrenamiento...')
#Entrenamos el modelo
historial = modelo.fit(celcius, f, epochs=1000, verbose=False)
print('Ya esta entrenado el modelo')

import matplotlib.pyplot as plt
plt.xlabel('Numero de vueltas')
plt.ylabel('Magnitud de perdida')
plt.plot(historial.history['loss'])

print('Probando el modelo de prediccion')
resultado = modelo.predict([100.0])
print('100 grados celcius a farenheit son: '+str(resultado))

